#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "test" "test" ;;
	2) notify-send "test" "test" ;;
	3) notify-send "Battery" "$(acpi)" ;;
	4) xbacklight -inc 10 ;;
	5) xbacklight -dec 10 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

for battery in /sys/class/power_supply/BAT?; do
	capacity=$(cat "$battery"/capacity 2>/dev/null) || break
	status=$(sed "s/Charging/\ CHR/;s/Discharging/\ DIS/;s/Full//;s/Not charging/\ NOT/;s/Unknown/\ UN/" "$battery"/status)

	printf "<span "

	[ "$status" = " CHR" ] || [ "$status" = "" ] && printf "foreground='#665c54'"
	if [[ "$status" = " DIS" ]]; then
		[ "$capacity" -lt 15 ] && printf "background='#cc241d'"
		[ "$capacity" -lt 30 ] && printf "foreground='#cc241d'"
		[ "$capacity" -lt 40 ] && printf "foreground='#d65d0e'"
		[ "$capacity" -lt 60 ] && printf "foreground='#d79921'"
		[ "$capacity" -ge 60 ] && printf "foreground='#98971a'"
	fi

	if [[ "$status" = " UN" ]]; then
		printf "background='#b16286'"
	fi

	#if [[ "$status" = " CHR" ] || [ "$status" = "" ]]; then
	#	printf "foreground='#665c54'"
	#elif [[ "$status" = " DIS" ]]; then
	#	[ "$capacity" -lt 15 ] && printf "background='#cc241d'"
	#	[ "$capacity" -lt 30 ] && printf "foreground='#cc241d'"
	#	[ "$capacity" -lt 40 ] && printf "foreground='#d65d0e'"
	#	[ "$capacity" -lt 60 ] && printf "foreground='#d79921'"
	#	[ "$capacity" -ge 60 ] && printf "foreground='#98971a'"
	#elif [[ "$status" = " UN" ]]; then
	#	printf "background='#b16286'"
	#fi

	printf ">BAT:%s" "$capacity"
	printf "%s" "$status"
	printf "</span>\n"

done

